FROM registry.fedoraproject.org/fedora:33

RUN dnf update -y && \
        dnf install -y \
        btrfs-progs-devel \
        device-mapper-devel \
        golang \
        gpgme-devel \
        make

ENV GOPATH=/
WORKDIR /src/github.com/containers/skopeo
